// <auto-generated />
namespace cizgiromandukkani.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class musteri : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(musteri));
        
        string IMigrationMetadata.Id
        {
            get { return "202005251056392_musteri"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
